# Generated by Django 5.1.2 on 2024-12-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_enrollment_alter_subject_students'),
        ('users', '0002_alter_enrollment_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
