# Generated by Django 5.1.4 on 2025-01-02 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_enrollment_options_alter_enrollment_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
